title: My First Blog          
description: A blog dedicated to educational content only. Is is beeing used as part of an test, which needs to be done for an exam.
author: IGross2022
theme: jekyll-theme-slate

github_username: IGross2022

